### ISSUE TITLE
feral attack power 

### ISSUE THREAD

**Issue by Sigols** [raethkcj/RatingBuster#31] opened 2021-06-13 21:19 UTC
Hi...
The druid's agility does not turn into feral attack power!

mfg Thomas

ps: nice Addon thx

sry for bad english (google)

**Comment by raethkcj** [comment] 2021-06-14 03:37
Hello,

This addon relies heavily on translations to read the stats on items in other languages. Would you mind sharing which language you play the game in?

Thanks!

**Comment by Sigols** [comment] 2021-06-14 11:27
Hi
i play with the german client

**Comment by trickdaemon** [comment] 2021-06-14 15:37
Hi, this is also an issue with the English client.
Previously in the 2.4.3 version I used to use on private servers it would only show agi into FAP while you're in cat form, as you don't receive attack power from agi in bearform. 
Thank you!

**Comment by aeadio** [comment] 2021-06-19 17:35
Can confirm, on the current enUS client, attack power calculation is not working, not just for feral. The above PR is correct, but doesn't fix the underlying issue. Agility->AP conversion seems to be broken, and direct +AP calculations sometimes do not work, both for feral AP and normal AP. 

Feral-only AP ("increases AP in bear/cat/moonkin") does work, and strength->AP works. 

See attached screenshots, all taken with @trickdaemon's fix above. 

![WoWScrnShot_061921_132741](https://user-images.githubusercontent.com/38795139/122650857-2c1ae800-d103-11eb-8a1b-ca1ccef2f18a.jpg)
![WoWScrnShot_061921_132748](https://user-images.githubusercontent.com/38795139/122650858-2cb37e80-d103-11eb-8eb2-ed5518f78ba4.jpg)
![WoWScrnShot_061921_132947](https://user-images.githubusercontent.com/38795139/122650859-2cb37e80-d103-11eb-92c7-3e7fcac52354.jpg)
![WoWScrnShot_061921_132950](https://user-images.githubusercontent.com/38795139/122650860-2cb37e80-d103-11eb-9374-27cb9ad883ef.jpg)
![WoWScrnShot_061921_133050](https://user-images.githubusercontent.com/38795139/122650861-2cb37e80-d103-11eb-823c-ea75d98a6724.jpg)

**Comment by aeadio** [comment] 2021-06-19 18:07
Tested my PR above and the issue is fixed. 

Agility -> AP conversion only happens when _in_ Cat Form. This is annoying, but is in line with how RatingBuster originally functioned. StatLogic's API doesn't give any good mechanism for querying what the AP would be under different scenarios, like the player being in Cat Form. 

For RatingBuster's purposes, I think it would be valuable to show these values at all times once Cat Form is learned. I think the Stat Logic API should be extended to account for this. I think Cat Form is the only exceptional situation like this, so it should be simple, and we can probably just tack on an optional parameter to :GetAPPerAgi() that always returns the shifted value. But if there's any other situations like this I'm not aware of, this might not be the right approach.

**Comment by aeadio** [comment] 2021-06-19 18:53
Looking into it, I was considering updating the APIs to take a "formid" parameter and assume that form for all calculations. That prompted me to check out stamina and armor modifications for Bear Form, and opened up a can of worms -- Druids have a _bunch_ of modifications per-form stemming from talents, and it all comes from the StatMods API. 

The StatMods API inherently assumes you're expecting the _current_ player conditions, such as buffs and talents learned. It doesn't even have a concept of shapeshift IDs, but just keys off active buff ID for Bear Form / Dire Bear Form. Hacking it to return modified values for shapeshift forms but not for anything else is a really bad approach. It also needs to be vetted for accuracy in tandem, because it's using a whole slew of hardcoded aura/spell IDs and spellbook pages/tabs, which are probably different between BCC and the original TBC client. 

I think the correct approach to get the StatLogic side able to spit out the information wanted, would be to augment StatMods so that it can be supplied with some data structure describing the target state for which to perform its calculations -- ie, hand it a table saying "user is in Bear Form and has these buffs/talents/etc". 

This is way out of scope of my available free time. 

At the very least, I think an issue should be raised to audit the contents of the stat mods table and ensure all those hardcoded values are correct. Ie, stamina modifications in Bear Form _aren't_ working as-is, at least going off what RatingBuster displays in the tooltip for items with +stamina on them.

**Closed** 2021-06-19 21:24 UTC
