### ISSUE TITLE
same error on 1.07

### ISSUE THREAD

**Issue by nofunnybao** [raethkcj/RatingBuster#23] opened 2021-06-04 15:49 UTC
two errors:
19x ...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua:190: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:190: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:185>
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML\PaperDollFrame.lua"]:1516: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
-----------------------------------------------------------------------------------------
1x ...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua:238: attempt to call method 'GetObjectType' (a nil value)
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:238: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:233>
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:351: in function `Hook'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1328: in function <RatingBuster\RatingBuster.lua:1326>
[string "=[C]"]: ?
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by raethkcj** [comment] 2021-06-07 13:58
Duplicate of #8

**Closed** 2021-06-07 14:04 UTC
Labels: bug, duplicate
