### ISSUE TITLE
[Bug]: Multiple Russian locale bugs

### ISSUE THREAD

**Issue by Mard35** [raethkcj/RatingBuster#120] opened 2022-11-11 23:55 UTC
I tested my settings profile on the Russian and English game client and found a lot of bugs of Russian locale. It turned out that part of stat conversions in Russian localization never worked and does not work to this day. Here is a screenshot of the same item in English and Russian localization

![en-ru_compare](https://user-images.githubusercontent.com/61734903/201443727-8c5fe185-0dce-49c0-ae77-3b480307d96e.jpg)

1)	Armor to AP conversion from Bladed Armor / Armored to the Teeth talents does not work and has never worked in Russian localization, although it works fine in English localization (screenshot above). Even after i provided declensions for armor, still doesn’t work for gear, but it works fine for armor consumables.

![armor-cosume](https://user-images.githubusercontent.com/61734903/201443893-db711b8d-a719-417f-bd46-abb26976d915.jpg)

2)	Armor penetration rating conversion doesn’t work in RU locale but it works fine in English localization (1st screenshot above). 
3)	Attack power is converted to x2 Attack power as strength. Attack power in russian is "Сила атаки" and strength is "Сила", but addon sees only word "Сила" in attack power and counts it as strength and converts to AP again.

![AP-bug1](https://user-images.githubusercontent.com/61734903/201444041-c38d6b49-fa8c-4544-a4e8-0178f854be32.jpg)
![AP-bug2](https://user-images.githubusercontent.com/61734903/201444061-4dd2df02-e2e5-4155-91f5-d407d6df85a0.jpg)

4)	Strength is converted to block chance for some reason, instead of block value. In Russian it should be just «Блок»
I mean it’s converted correctly but using wrong stat name.

![block](https://user-images.githubusercontent.com/61734903/201444552-71846566-3e0c-4d79-9896-470e970a8488.jpg)

5)	Not exactly a bug, but misleading: Defense breakdown to % x 5 is incorrect. Crit Avoidance should not be here because it’s not a real avoidance which is summed up with all the dodge, parry, block and miss. Little example: item has 49 defense rating, it’s a 0.4% dodge, 0.4% parry, 0.4% block, 0,4% miss which means 0.4 x 4 = 1.6% Total avoidance. Yes, it gives 0.4 % crit avoidance too, but Total is still 1.6% = 0.4 x 4. But your addon says it’s 0.40% x 5 which is incorrect. Nobody needs crit avoidance here, it's just confusing and misleading, please just remove crit avoidance from breakdown and let it be x4 instead of x5.

![defense-breakdown](https://user-images.githubusercontent.com/61734903/201444785-ee8e047d-1e89-4d91-a8a9-c7f49b05da3a.jpg)

6)	Final suggestion: look how compact English tooltip looks like with short stat and rating names. And how ugly Russian tooltip looks like because of too long rating names.

![compact-tt](https://user-images.githubusercontent.com/61734903/201444959-3539a64e-239f-4881-b152-ff682a167bee.jpg)
![long-tt](https://user-images.githubusercontent.com/61734903/201444968-12d22adb-c244-4489-84ed-f2cfdd45638a.jpg)

 All these «к вер. крит. удара» and «к вер. уклонения» etc are toooo long and huge. You can easily shorten them. For example: instead of using «к вер. крит. удара» you can use «Крита» like you doing this in English. You can even use English words, we will undesrstand that. Every Russian knows English stat names, we are using english stat names in our speech and theorycrafting, we don’t even need stat translation from addon, only conversion is needed. You are free to not translate stat names in tooltips.
Sorry for my bad English.

### Addon Source

GitHub Releases

### Version

1.6.3

### Locale

Russian

### Talent Specialization

Protection Warrior

### Race

Undead

**Comment by Mard35** [comment] 2022-11-13 06:35
In addition to bug № 2: Armor penetration rating contains the word «брони» and addon thinks it’s literally armor and converts it to AP bonus because of Armored to the Teeth talent for Fury warrior.

![arp-bug](https://user-images.githubusercontent.com/61734903/201509062-512a2baa-6677-456e-a9f3-bce847f1658f.jpg)

In addition to bug № 3: Attack power is also converted to block chance because of the word «силу» 

![ap-bug2](https://user-images.githubusercontent.com/61734903/201509068-968908e3-3094-4250-84d0-846f975c1ae8.jpg)

Addon just goes crazy with the Russian language)

**Comment by Mard35** [comment] 2022-11-13 09:19
Ok, i fixed bug № 2, 3, 4 bugs by myself. It was pretty easy. It's so funny that you are violating your own addon rules in locale files. It says in comments "longer strings should be listed first" but your AP and armor penetration rating was on LAST places. So i moved them at first place and did some other moving and renaming. Check the file i linked.
I still failed to fix Armor to AP conversion from Bladed Armor / Armored to the Teeth talents on gear. There is something wrong with stat scanning in statlogic. 
Also i found a lot of missing translation and misunderstanding how the Russian language works in ruRU.lua files
[RatingBuster ruRU fixed.txt](https://github.com/raethkcj/RatingBuster/files/9996821/RatingBuster.ruRU.fixed.txt)

**Comment by raethkcj** [comment] 2022-11-13 13:56
You're welcome to open a pull request if you want to contribute. The translations that exist for Russian are generous contributions from users, as you saw in #9. Every language besides English requires 3rd-party translations to function. I maintain this addon for my own enjoyment in my own free time, I'm not here to waste time bickering with you.

If you have fixes for issues 1-4 then I will happily consider them in a pull request. 5 is working as intended and can be configured in the addon settings. For 6 I would accept shorter Russian strings if you feel you can make them more clear, but I won't be changing them to English.

**Comment by Mard35** [comment] 2022-11-13 17:54
Ok, I am not a programmer, i created a pull request. Is it correct? 
I can't fix 1st bug with armor by myself. Could you briefly explain to me how statlogic works?
5th is working as intended, but it's not correctly intended (i explained above why). I want to remove crit avoidance from breakdown, but i still want to see other x4 avoidances. I can't configure it in options.

**Comment by raethkcj** [comment] 2022-11-15 20:43
Thanks, I've merged your changes and fixed the missing Armor breakdown. The colon was causing the problem. I've put your request for Defense breakdown in a separate Feature Request.

**Closed by raethkcj** 2022-11-15 20:43 UTC
Labels: bug
