### ISSUE TITLE
Tooltip Error with DK

### ISSUE THREAD

**Issue by kealsera** [raethkcj/RatingBuster#92] opened 2022-09-11 06:09 UTC
Greetings,

im getting this Error Message when hovering over Items (any) - but just with my DK only. 
It works fine with every other class.
```

Message: Interface\AddOns\StatLogic\StatLogic.lua:1184: Usage: GetShapeshiftFormInfo(index)
Time: Sun Sep 11 08:06:47 2022
Count: 2
Stack: Interface\AddOns\StatLogic\StatLogic.lua:1184: Usage: GetShapeshiftFormInfo(index)
[string "=[C]"]: ?
[string "@Interface\AddOns\StatLogic\StatLogic.lua"]:1184: in function `validator'
[string "@Interface\AddOns\StatLogic\StatLogic.lua"]:1207: in function <Interface\AddOns\StatLogic\StatLogic.lua:1202>
[string "@Interface\AddOns\StatLogic\StatLogic.lua"]:1253: in function <Interface\AddOns\StatLogic\StatLogic.lua:1252>
[string "@Interface\AddOns\StatLogic\StatLogic.lua"]:1300: in function <Interface\AddOns\StatLogic\StatLogic.lua:1290>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1938: in function <Interface\AddOns\RatingBuster\RatingBuster.lua:1715>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1678: in function `ProcessLine'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1560: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame_Shared.lua"]:1333: in function `UpdateTooltip'
[string "@Interface\FrameXML\GameTooltip.lua"]:429: in function <Interface\FrameXML\GameTooltip.lua:408>

Locals: (*temporary) = 0

```

**Comment by raethkcj** [comment] 2022-09-11 11:58
This was fixed about a week ago, make sure to update.

Duplicate of #89

**Closed by raethkcj** 2022-09-11 11:58 UTC

**Comment by kealsera** [comment] 2022-09-12 05:22
The version you pushed to wowup after closing this worked, the other one was 6d old and still had this issue. Thanks!

**Comment by raethkcj** [comment] 2022-09-12 12:55
Wowup seems to be having trouble picking up versions this week; Questie was also out-of-date there but updated elsewhere. Authors don't manually push there so not much to be done about it I guess.
